/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 digital.gltf --transform
Author: besturkan (https://sketchfab.com/besturkan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/social-media-scene-87d70f5353ae41afb3502d64475e6e6d
Title: Social Media Scene
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/digital-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.582, -0.128, -0.762]} scale={[1, 2.964, 1]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.PaletteMaterial002} position={[0, 2.267, 0.022]} scale={[0.938, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/digital-transformed.glb')
