/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 game.gltf --transform
Author: LamedeFeu (https://sketchfab.com/lamedefeu)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/windmill-game-ready-6a006afce57a447baa60c7a6791f0086
Title: Windmill (game ready)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/game-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_4" scale={0.01}>
          <group name="RING" position={[-0.382, 2.493, 1.438]}>
            <mesh name="RING_standardSurface1_0" geometry={nodes.RING_standardSurface1_0.geometry} material={materials.standardSurface1} />
          </group>
        </group>
        <group name="_rootJoint" scale={0.01}>
          <group name="joint1_00" position={[-0.382, 0.442, 1.439]} rotation={[0, 0, Math.PI / 2]}>
            <group name="joint2_01" position={[2.626, 0, 0]} rotation={[-0.419, 0, 0]}>
              <group name="joint3_02" position={[1.675, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <group name="polySurface142" position={[-0.051, 2.453, 4.324]} rotation={[-2.391, 0.294, 0]}>
                  <mesh name="polySurface142_standardSurface1_0" geometry={nodes.polySurface142_standardSurface1_0.geometry} material={materials.standardSurface1} />
                </group>
              </group>
              <group name="UPPER" position={[-3.068, 0.236, -1.469]} rotation={[0.419, 0, -Math.PI / 2]}>
                <mesh name="UPPER_standardSurface1_0" geometry={nodes.UPPER_standardSurface1_0.geometry} material={materials.standardSurface1} />
              </group>
            </group>
            <group name="polySurface148" position={[-0.442, -0.382, -1.439]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh name="polySurface148_standardSurface1_0" geometry={nodes.polySurface148_standardSurface1_0.geometry} material={materials.standardSurface1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/game-transformed.glb')
